# Bash-style exports, to be sourced from within the "usdpaa" tree
# when developing and building locally (rather than via ltib).
#
# Note, it hard-codes a toolchain path to that currently installed
# by ltib (so adjust as required).
#
# Note also, it hard-codes include and lib paths to the rootfs
# staging area managed by ltib, assuming that this usdpaa tree
# is a sibling of the ltib tree (again, adjust as required).

# The target architecture
ARCH := powerpc

# The path to the cross compilation tools
CROSS_TOOLS_PATH := /opt/freescale/usr/local/gcc-4.3.74-eglibc-2.8.74-dp-2/powerpc-none-linux-gnuspe/bin

# The prefix for compilation directives
CROSS_COMPILE := $(CROSS_TOOLS_PATH)/powerpc-none-linux-gnuspe-

